Add test programs for AFUs IBM,MEMCPY3 and IBM,AFP3
OpenCAPI/libocxl pull request #17
Opened 2018-10-15 14:36 UTC by philippe56

2018-10-15 22:32 UTC, deece requested changes
Please add the afutests directory to the 'precommit' target in the Makefile, then run 'make precommit'. I'm not sure if it will join statements that have been manually split (wrapped at 80 cols), so these may have to be joined manually before running precommit.

2018-10-15 22:32 UTC, deece commented on afutests/afp/ocxl_afp3.c
> + *
Should this be 2018?

2018-10-15 22:32 UTC, deece commented on afutests/afp/ocxl_afp3.c
> +	       >= 0) {
Unsplit this line for readability

2018-10-15 22:32 UTC, deece commented on afutests/memcpy/README.md
> +
Could we add a link here to help the user find where to get the image?

2018-10-17 13:23 UTC, philippe56 commented on afutests/afp/ocxl_afp3.c
> + *
Correct. Fixed in commit 158b58e below.

2018-10-18 22:49 UTC, deece approved these changes

2018-10-18 22:50 UTC, merged